FROM jupyter/minimal-notebook

RUN python -m pip install --upgrade pip
RUN pip install --upgrade setuptools
RUN pip install python-magic altair vincent geopandas folium psycopg2-binary sqlacodegen openpyxl simplejson xeus-python